import pickle
from pathlib import Path

import faiss
from sentence_transformers import SentenceTransformer


# ------------------------------------------------------------
# 1. Basic configuration
# ------------------------------------------------------------

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

PROJECT_ROOT = Path(__file__).resolve().parents[1]

INDEX_DIR = PROJECT_ROOT / "models" / "faiss_index"
INDEX_PATH = INDEX_DIR / "reviews.index"
METADATA_PATH = INDEX_DIR / "review_metadata.pkl"


# ------------------------------------------------------------
# 2. Validation helper
# ------------------------------------------------------------

def validate_faiss_files():
    """
    Check that the FAISS index and metadata files exist.

    These files are generated by:
        python src/build_faiss_index.py

    They are usually stored under:
        models/faiss_index/
    """

    missing_files = []

    if not INDEX_PATH.exists():
        missing_files.append(str(INDEX_PATH))

    if not METADATA_PATH.exists():
        missing_files.append(str(METADATA_PATH))

    if missing_files:
        missing_text = "\n".join(missing_files)

        raise FileNotFoundError(
            f"Missing FAISS retrieval files:\n"
            f"{missing_text}\n\n"
            f"Run this command from the project root first:\n"
            f"python src/build_faiss_index.py"
        )


# ------------------------------------------------------------
# 3. FAISS retriever class
# ------------------------------------------------------------

class FaissReviewRetriever:
    """
    Loads a saved FAISS index and retrieves reviews that are semantically
    similar to a user query.
    """

    def __init__(self):
        validate_faiss_files()

        print("Loading embedding model...")
        self.embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

        print("Loading FAISS index...")
        self.index = faiss.read_index(str(INDEX_PATH))

        print("Loading metadata...")
        with open(METADATA_PATH, "rb") as f:
            self.metadata = pickle.load(f)

        self._validate_index_metadata_alignment()

    def _validate_index_metadata_alignment(self):
        """
        Ensure that every vector in the FAISS index has matching metadata.
        """

        index_size = self.index.ntotal
        metadata_size = len(self.metadata)

        if index_size != metadata_size:
            raise ValueError(
                f"FAISS index and metadata size mismatch.\n"
                f"Index vectors: {index_size}\n"
                f"Metadata rows: {metadata_size}\n\n"
                f"Rebuild the index with:\n"
                f"python src/build_faiss_index.py"
            )

    def retrieve(self, query, top_k=3):
        """
        Retrieve the top_k most similar reviews for a user query.

        Parameters:
            query:
                The user's input text.

            top_k:
                Number of similar reviews to retrieve.

        Returns:
            A list of dictionaries containing:
                - rank
                - score
                - text
                - original label
                - sentiment
        """

        if not query or not query.strip():
            return []

        top_k = min(top_k, self.index.ntotal)

        query_embedding = self.embedding_model.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True,
        )

        query_embedding = query_embedding.astype("float32")

        scores, indices = self.index.search(query_embedding, top_k)

        results = []

        for rank, (score, index_position) in enumerate(
            zip(scores[0], indices[0]),
            start=1,
        ):
            # FAISS can return -1 if no valid result exists.
            if index_position == -1:
                continue

            item = self.metadata[index_position]

            results.append(
                {
                    "rank": rank,
                    "score": float(score),
                    "text": item["text"],
                    "label": item["label"],
                    "sentiment": item["sentiment"],
                }
            )

        return results

    def retrieve_with_sentiment_filter(
        self,
        query,
        sentiment,
        top_k=3,
        candidate_k=10,
    ):
        """
        Retrieve semantically similar reviews and prefer results with the same
        sentiment as the user's final predicted sentiment.
        """

        candidate_k = max(candidate_k, top_k)

        candidates = self.retrieve(
            query=query,
            top_k=candidate_k,
        )

        sentiment_matches = [
            result
            for result in candidates
            if result["sentiment"] == sentiment
        ]

        selected_results = sentiment_matches[:top_k]

        if len(selected_results) < top_k:
            selected_texts = {result["text"] for result in selected_results}

            fallback_results = [
                result
                for result in candidates
                if result["text"] not in selected_texts
            ]

            needed = top_k - len(selected_results)

            selected_results.extend(fallback_results[:needed])

        for rank, result in enumerate(selected_results, start=1):
            result["rank"] = rank

        return selected_results 

# ------------------------------------------------------------
# 4. Manual test
# ------------------------------------------------------------

if __name__ == "__main__":

    retriever = FaissReviewRetriever()

    test_query = "The food arrived cold and the delivery was very late."

    print("=" * 80)
    print("Query:")
    print(test_query)
    print("=" * 80)

    results = retriever.retrieve_with_sentiment_filter(
        query=test_query,
        sentiment="negative",
        top_k=3,
        candidate_k=10,
    )

    for result in results:
        print()
        print(f"Result {result['rank']}")
        print("-" * 80)
        print(f"Score: {result['score']:.4f}")
        print(f"Sentiment: {result['sentiment']}")
        print(f"Original Yelp label: {result['label']}")
        print(f"Review text: {result['text'][:700]}")